apiVersion: apps/v1
kind: Deployment
metadata:
  name:  hello-rancher
  namespace: default
  labels:
    app:  hello-rancher
spec:
  selector:
    matchLabels:
      app: hello-rancher
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  hello-rancher
    spec:
      containers:
      - name:  hello-rancher
        image: peteindockerhub/hello-rancher:1.0.2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        env:
        - name: CONTAINER_COLOR
          value: blue
        - name: PETS
          value: chameleons
          # cows
          # chameleons
          # cowmeleons
        ports:
        - containerPort:  8080
      restartPolicy: Always
