apiVersion: v1
kind: Service
metadata:
  name: hello-rancher
  namespace: default
spec:
  selector:
    app: hello-rancher
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
